# ~ Main Settings

BOARD-ENABLED: true
TAB-ENABLED: true
LUNAR-ENABLED: true

# ~ Chat Settings

CHAT:
  ENABLED: true
  FORMAT: "%vault_prefix% %player_name%&7: %message%"

# ~ Lunar Settings

NAME-TAGS:
  - "&6[&7Kills: &f%statistic_player_kills% &8┃ &f%player_colored_ping%ms&6]"
  - "%aqua_player_rank_color% %player_name%"